version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
    nodejs: "20"
  jobs:
    post_create_environment:
      - npm install -g jsdoc

# install doxygen >= 1.9.2
conda:
  environment: .readthedocs.condaenv.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf

python:
  install:
    - method: setuptools
      path: docs/rtd_pyqbdi_artifact
