name: Code format

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      CLANG_FORMAT_VERSION: 14
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system dependencies
        run: |
          sudo apt install -y --no-install-recommends clang-format-${{ env.CLANG_FORMAT_VERSION }}
          python3 -m pip install cmakelang
      - name: Check format
        run: bash ./.github/format_check.sh


